### ISSUE TITLE
Integrate this repo into jamwaffles/organisations-rs

### ISSUE THREAD

**Issue by jamwaffles** [repositive/event-store-rs#12]
Integrate with something like this in `Cargo.toml`:

```toml
[dependencies]

[dependencies.event-store-rs]
git = "https://github.com/jamwaffles/event-store-rs"
```

You may also want to add a `rev = "<commit hash>"` to lock the dep to a known-working version.
